### ISSUE TITLE
Input Validations check for Empty element 

### ISSUE THREAD

**Issue by theobiabo** [blackgirlbytes/time-blind#1]
I Noticed an issue:

- Its adding Empty list

STEP TO PRODUCE. 

Leave Input field empty and click on Add Task 
It will add an empty item to the list 
![Screenshot from 2023-08-01 23-13-20](https://github.com/blackgirlbytes/time-blind/assets/54102389/5870c15e-a6c1-4aa5-a0e7-a50df268b104)

**Comment by blackgirlbytes** [comment]
I fixed this! Thank you for pointing this out @yhoungdev

**Comment by blackgirlbytes** [comment]
You can see that I made this update here: https://github.com/blackgirlbytes/time-blind/commit/4c50d8cdb37c752d4dc8c2e6af0bb8931d49d942#diff-26ca35c3be6d07c84bb77f1e63a1b19487279d5b9c9a9392179b3a35647e1254R57

**Comment by theobiabo** [comment]
Yea awesome. i saw the update and also tested it. 
Its working perfectly.

And also i could see you are using web5 instance.
i think this is a good time i read about that
![Screenshot from 2023-08-06 17-37-57](https://github.com/blackgirlbytes/time-blind/assets/54102389/93bd7960-eee1-4269-a330-0a4ccbe32bdb)

I could remember Angie speaking about that
